language: node_js
node_js:
  - "stable"
  - "4.1"
  - "0.12"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

install:
  # skip the "prepublish" hook because we want finer control
  - npm install --ignore-scripts
  - npm link
  - npm run build # build failures should count!

  # install npm dependencies for all packages and make sure they are compilable
  - (cd packages/git; npm link tinydoc)
  - ./bin/prepublish.sh git       -S test -S lint

  # tinydoc-plugin-js:
  # we need to link it as well because tinydoc-plugin-react depends on it:
  - (cd packages/git; npm link tinydoc)
  - ./bin/prepublish.sh js        -S test -S lint
  - (cd packages/tinydoc-plugin-js; npm link)

  # tinydoc-plugin-lua:
  - (cd packages/git; npm link tinydoc)
  - ./bin/prepublish.sh lua       -S test -S lint

  # tinydoc-plugin-markdown:
  - (cd packages/git; npm link tinydoc)
  - ./bin/prepublish.sh markdown  -S test -S lint

  # tinydoc-plugin-react:
  - (cd packages/git; npm link tinydoc; npm link tinydoc-plugin-js)
  - ./bin/prepublish.sh react     -S test -S lint

  # tinydoc-plugin-yard-api:
  - (cd packages/git; npm link tinydoc)
  - ./bin/prepublish.sh yard-api  -S test -S lint

script:
  - ./bin/lint.sh
  - ./bin/lint-ui.sh
  - COVERAGE=1 ./bin/test.sh
  - ./node_modules/.bin/karma start --single-run --browsers Firefox

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

env:
  - TINYDOC_TEST_TIMEOUT=60000