sudo: false
language: node_js
node_js:
  - "stable"
  - "7"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

install:
  - ./bin/setup

script:
  - COVERAGE=1 MEGADOC_TEST_TIMEOUT=60000 ./bin/lerna-prepublish
  - npm run doc

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
