sudo: false
language: node_js
node_js:
  - "stable"
  - "5.11.0"
  - "4.4.3"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

install:
  - PRELINK=1 ./bin/setup

script:
  - ./bin/lint
  - ./bin/lint-ui
  - COVERAGE=1 ./bin/test
  - ./bin/test-ui --single-run --browsers Firefox

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

env:
  - MEGADOC_TEST_TIMEOUT=60000 TRAVIS_BUILD=1

cache:
  directories:
    - node_modules