language: node_js
node_js:
  - "stable"
  - "4.1"
  - "0.12"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

install:
  # skip the "prepublish" hook because we want finer control
  - npm install --ignore-scripts
  - npm run build # build failures should count!

  # install npm dependencies for all packages and make sure they are compilable
  - ./bin/prepublish.sh git       -S test -S lint
  - ./bin/prepublish.sh js        -S test -S lint
  - ./bin/prepublish.sh lua       -S test -S lint
  - ./bin/prepublish.sh markdown  -S test -S lint
  - ./bin/prepublish.sh react     -S test -S lint
  - ./bin/prepublish.sh yard-api  -S test -S lint

script:
  - ./bin/lint.sh
  - ./bin/lint-ui.sh
  - ./bin/test.sh
  - npm run test:ui -- --browsers Firefox
  - COVERAGE=1 ./bin/test.sh

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
