sudo: false
language: node_js
node_js:
  - "stable"

install:
  - npm install --ignore-scripts
  - ./node_modules/.bin/lerna bootstrap

script:
  - ./bin/scan-dependency-versions
  - ./bin/lint
  - ./bin/lint-ui
  - ./node_modules/.bin/lerna exec --concurrency 1 --stream -- NODE_ENV=production PACKAGE="${LERNA_PACKAGE_NAME}" ../../bin/prepublish -S test -S lint
  - COVERAGE=1 MEGADOC_TEST_TIMEOUT=60000 ./bin/test
  - npm run doc

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
