language: node_js
node_js:
  - "stable"
  - "iojs"
  - "4.1"
  - "0.12"
  - "0.11"
  - "0.10"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

install: npm install --ignore-scripts

script:
  - PACKAGE=git ./bin/prepublish -S test -S lint
  - PACKAGE=js ./bin/prepublish -S test -S lint
  - PACKAGE=lua ./bin/prepublish -S test -S lint
  - PACKAGE=markdown ./bin/prepublish -S test -S lint
  - PACKAGE=react ./bin/prepublish -S test -S lint
  - PACKAGE=yard-api ./bin/prepublish -S test -S lint
  - npm run lint
  - npm run lint:ui
  - npm run test
  - npm run test:ui -- --browsers Firefox
  - npm run build # build failures should count!
  - npm run coverage

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
