sudo: false
language: node_js
node_js:
  - "stable"
  - "5.11.0"
  - "4.4.3"
  - "0.12"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

install:
  # skip the "prepublish" hook because we want finer control
  - npm install --ignore-scripts
  - npm link --ignore-scripts
  - npm run build # build failures should count!
  - SKIP_SELF_PREPUBLISH=1 PRELINK=1 ./bin/prepublish-all.sh

script:
  - ./bin/lint.sh
  - ./bin/lint-ui.sh
  - COVERAGE=1 ./bin/test.sh
  - ./bin/test-ui.sh --single-run --browsers Firefox

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

env:
  - TINYDOC_TEST_TIMEOUT=60000 TRAVIS_BUILD=1

cache:
  directories:
    - node_modules