language: node_js
node_js:
  - "stable"
  - "iojs"
  - "4.1"
  - "0.12"
  - "0.11"
  - "0.10"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

install:
  - npm install --ignore-scripts
  - PACKAGE=git ./bin/prepublish.sh -S test -S lint
  - PACKAGE=js ./bin/prepublish.sh -S test -S lint
  - PACKAGE=lua ./bin/prepublish.sh -S test -S lint
  - PACKAGE=markdown ./bin/prepublish.sh -S test -S lint
  - PACKAGE=react ./bin/prepublish.sh -S test -S lint
  - PACKAGE=yard-api ./bin/prepublish.sh -S test -S lint

script:
  - npm run lint
  - npm run lint:ui
  - npm run test
  # disabling this for now, something to do with:
  #     Error: Cannot find module "../tmp/publicModules"
  # - npm run test:ui -- --browsers Firefox
  - npm run build # build failures should count!
  - npm run coverage

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
